---
- name: Verify Linux distribution version
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Ubuntu'
      - ansible_facts['distribution_major_version'] == '22'
    fail_msg: "Supports Ubuntu versions 22. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}."
    success_msg: "Running on Ubuntu {{ ansible_facts['distribution_major_version'] }}."
